# DO NOT change the base image, it has an environment built for using Claude Code inside of a Devcontainer and must not be changed
# flash-attn v 2.7.4.post1 is already installed, DO NOT reinstall it
FROM uehreka/devcontainer-base:pytorch2.7.0-cuda12.8-node22-ubuntu22.04

USER root

# Put any commands that need to be run as root here

USER node

# The user must be set back to "node" before

